source $HOME/.zshenv

# SSH key setup ...
for KEY_FILE in $HOME/.ssh/*.ssh
do
  keychain $KEY_FILE
done

source $HOME/.keychain/$HOST-sh

ulimit -n 10000
export LESSOPEN="| $(which highlight) %s --out-format xterm256 --line-numbers --quiet --force --style solarized-dark"
export LESS=" -R"
alias less='less -m -N -g -i -J --line-numbers --underline-special'
alias more='less'
alias gw='./gradlew'
alias grepl='gw javarepl --console plain --no-daemon'
