---
- hosts: all
  vars:
    tmp_dir: ~/tmp
 
  pre_tasks:
    - file: path={{ tmp_dir }} state=directory mode=0700
    - file: path=~/.ssh state=directory mode=0700
    - file: path=~/Documents/projects state=directory mode=0700
    - homebrew_tap: tap=caskroom/versions state=present
 
  roles:
    - { role: finder }
    - { role: dropbox, sudo: yes }
    - { role: 1password, sudo: yes }
    - { role: alfred, sudo: yes }
    - { role: comms, sudo: yes}
    - { role: keychain }
    - { role: iterm2 }
    - { role: tmux }
    - { role: git }
    - { role: java }
    - { role: dash }
    - { role: zsh }
    - { role: vim }
    - { role: emacs }
    - { role: vmware-fusion }
    - { role: vagrant }
    - { role: evernote }
    - { role: omnifocus }
    - { role: omnigraffle }
    - { role: chrome }
    - { role: flash }
    - { role: microsoft-office}
    - { role: xhyve }
    - { role: spotify }
    - { role: tools }
