---
- name: Install zsh and colordiff from Homebrew
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - colordiff
    - z
    - zsh
    - zsh-syntax-highlighting

- name: Add Homebrew's Zsh to available shells
  sudo: yes
  lineinfile:
    dest: /etc/shells
    line: "{{ homebrew_home }}/bin/zsh"

- name: Grab the oh-my-zsh directory stats
  stat:
    path: "{{ zsh_oh_my_zsh_home }}"
  register: oh_my_zsh_st

- name: Install oh-my-zsh
  git: 
    repo: "{{ zsh_oh_my_zsh_repo_url }}"
    dest: "{{ zsh_oh_my_zsh_home }}"
  when: not oh_my_zsh_st.stat.exists

- name: Grab the zsh-syntax-highlighting oh-my-zsh plugin directory stats
  stat:
    path: "{{ zsh_syntax_highlighting_plugin_home }}"
  register: zsh_syntax_highlighting_plugin_st

- name: Install zsh-syntax-highlighting oh-my-zsh plugin
  git: 
    repo: "{{ zsh_syntax_highlighting_plugin_repo_url }}"
    dest: "{{ zsh_syntax_highlighting_plugin_home }}"
  when: not zsh_syntax_highlighting_plugin_st.stat.exists

- name: Copy .profile and .zshrc to ~/
  copy: 
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  with_items:
    - profile
    - zshrc

- name: Check if Homebrew's Zsh is already the default shell (will require a restart)
  shell: echo $SHELL
  register: shell_name
  changed_when: shell_name.stdout != '{{ homebrew_home }}/bin/zsh'

- name: Make Homebrew's Zsh default shell for this user
  shell: chsh -s {{ homebrew_home }}/bin/zsh
  when: shell_name|changed

