---
- name: Install git from Homebrew
  homebrew: name=git state=present

- name: Install git-flow from Homebrew
  homebrew: name=git-flow state=present

- name: Install gist from Homebrew
  homebrew: name=gist state=present

- name: Install kaleidoscope from Homebrew Cask
  homebrew_cask: name=kaleidoscope state=present
  sudo: true

- name: Copy .gitignore into ~/
  copy: src=gitignore dest=~/.gitignore

- name: Copy .gitconfig into ~/
  copy: src=gitconfig dest=~/.gitconfig
