---
- name: Tap emacs-plus
  homebrew_tap:
    tap: d12frosted/emacs-plus

- name: Ensure Emacs is not installed
  homebrew:
    name: emacs
    state: absent

- name: Install emacs-plus
  homebrew:
    name: emacs-plus
    state: linked
    install_options: with-cocoa, with-gnutls, with-librsvg, with-imagemagick, with-spacemacs-icon
  notify:
    - restart emacs-plus server

- name: Install Cask + node and npm dependencies for Markdown live prevew + ispell
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - cask
    - coreutils
    - ispell
    - node
    - npm

- name: Install vmd for Markdown live preview
  npm:
    name: vmd
    global: true

- name: Install SCSS-Lint dependencies for the HTML layer
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: scss_lint, version: "~> 0.43.0" }
    - { name: scss_lint_reporter_checkstyle, version: "" }

- name: Create the ~/.emacs.d  directory
  file:
    path: "{{ emacs_conf_dir }}"
    state: directory

- name: Install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ emacs_conf_dir }}"
    version: "{{ spacemacs_version }}"
  notify:
    - restart emacs-plus server

- name: Copy spacemacs configuration into home directory
  copy:
    src: spacemacs
    dest: ~/.spacemacs
  notify:
    - restart emacs-plus server

- name: Install Python anaconda, syntax checking, linting, and hy-mode dependencies
  pip:
    name: "{{ item }}"
    state: present
    virtualenv_command: pyenv
  with_items:
    - "jedi>=0.9.0"
    - "json-rpc>=1.8.1"
    - "service_factory>=0.1.5"
    - autoflake
    - flake8
    - hy
    - enum34

- name: Add lein profile
  copy:
    src: lein-profile.clj
    dest: ~/.lein/profiles.clj


