---
- name: Install Java6, Java7, Java8, IntelliJ, and Java Decompiler
  homebrew_cask:
    name: "{{ item }}"
    state: present
  sudo: true
  with_items:
    - java6
    - java7
    - java
    - intellij-idea-ce
    - jd-gui

- name: Install jenv, Gradle, and Maven
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - jenv
    - gradle
    - maven
    - javarepl

- name: Create .gradle directory
  file: 
    path: ~/.gradle
    state: directory

- name: Enable the Gradle daemon
  lineinfile:
    dest: ~/.gradle/gradle.properties
    line: org.gradle.daemon=true
    create: true
    state: present

