---
- name: Install nmap and htop
  homebrew: name={{ item }} state=present
  with_items:
    - "htop-osx"
    - "ncdu"
    - "nmap"

- name: Install pydf
  shell: eval $(pyenv install) && pip install pydf
