---
- name: Install nmap and htop
  homebrew: 
    name: "{{ item }}" 
    state: present
  with_items:
    - "htop-osx"
    - "ncdu"
    - "nmap"
    - "ack"

- name: Install pydf
  pip:
    name: pydf
    virtualenv_command: pyenv

