---
- name: Install tmux and associated utilities from Homebrew
  package:
    name: tmux
    state: present
  become: True

- name: Install Mac clipboard integration
  package:
    name: reattach-to-user-namespace
    state: present
  when: ansible_os_family == "Darwin"

- name: Create the tmux plugin directory
  file:
    path: "{{ tmux_plugin_dir }}"
    state: directory

- name: Grab stats of the Tmux Plugin Manager directory
  stat:
    path: "{{ tmux_tpm_dir }}"
  register: tmux_tpm_dir_st

- name: Install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_tpm_dir }}"
    version: v3.0.0
  when: tmux_tpm_dir_st.stat.isdir is not defined

- name: Copy tmux.conf into ~/
  template:
    src: tmux.conf.j2
    dest: "/home/{{ ansible_ssh_user }}/.tmux.conf"

- name: Install tmux plugins
  shell: "{{ tmux_tpm_dir }}/bin/install_plugins"

