---
- name: Install tmux and associated utilities from Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - "tmux"
    - "reattach-to-user-namespace"

- name: Copy tmux.conf into ~/
  copy: src=tmux.conf dest=~/.tmux.conf
