---
- name: Install rbenv
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - rbenv
    - rbenv-bundler
    - rbenv-gemset
    - ruby-build

- name: Configure the default Ruby version
  copy:
    content: "{{ ruby_version }}"
    dest: ~/.ruby-version

- name: Init rbenv
  shell: rbenv init -

- name: Check Ruby versions
  shell: echo -e $(rbenv versions | grep "{{ ruby_version }}" | wc -l)
  register: ruby_version_installed

- name: Use rbenv to install Ruby
  shell: rbenv install "{{ ruby_version }}"
  when: ruby_version_installed == 0

- name: Install default gems
  gem:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ruby_default_gems }}"

